using GLOB.Domain.Base;

namespace GLOB.Domain.Global;

// Entity Specific to Hierarchy to Make Global
public class EntityShort : EntityBase
{
  // Generated by End User (PayStatus-Active, PayStatus-Deactive, Guids, 001-0002-0003)
  // Pregenerated Key Because of Applying Conditions on (Backend / FrontEnd)
  public string KeyId { get; set; } // Generated by End User
  public int? EntityShortParentId { get; set; }
  public virtual EntityShortParent? EntityShortParent { get; set; }
}
