using GLOB.Domain.Base;

namespace GLOB.Hierarchy.Global;

public class GlobalLookup : EntityBase
{
  // Generated by End User (PayStatus-Active, PayStatus-Deactive, Guids, 001-0002-0003)
  // Pregenerated Key Because of Applying Conditions on (Backend / FrontEnd)
  public string Code { get; set; } 
  public int? ProjectzLookupBaseId { get; set; }
  public virtual ProjectzLookupBase? ProjectzLookupBase { get; set; }
}
