using GLOB.Domain.Base;

namespace GLOB.Hierarchy.Global;

public class GlobalEntityLookup : EntityBase
{
  // Generated by End User (PayStatus-Active, PayStatus-Deactive, Guids, 001-0002-0003)
  // Pregenerated Key Because of Applying Conditions on (Backend / FrontEnd)
  public string KeyId { get; set; } 
  public int? ProjectzEntityLookupBaseId { get; set; }
  public virtual ProjectzEntityLookupBase? ProjectzEntityLookupBase { get; set; }
}
