using GLOB.Domain.Base;

namespace GLOB.Hierarchy.Global;

public class GlobalLookupz : EntityBase
{
  // Generated by End User (PayStatus-Active, PayStatus-Deactive, Guids, 001-0002-0003)
  // Pregenerated Key Because of Applying Conditions on (Backend / FrontEnd)
  public string Code { get; set; } 
  public int? ProjectzLookupzBaseId { get; set; }
  public virtual ProjectzLookupzBase? ProjectzLookupzBase { get; set; }
}
