################~~~~ SBA Auth ~~~~~##################
# - Deployment
# - ClusterIP
# - Node Port

## BASH BUILD Dockerfile
## -t tagname, -f file/reference, ./buildContext  
# docker build -t mansanhhub/srvc-sba-auth -f SBA.Auth/Dockerfile .
# docker push mansanhhub/srvc-sba-auth
# docker pull mansanhhub/srvc-sba-auth

#------------------------------------------------------------------------- 
## BASH RUN Deployment srvc-sba-auth
# kubectl apply -f ./__K8S/B_DEPL_SRVC/depl-sba-auth.yaml
# kubectl get pods
# kubectl get deployments
# kubectl logs -l app=srvc-sba-auth
# kubectl rollout restart deployments depl-sba-auth

## BASH DELETE (Deployments & Service)8
# kubectl delete -f ./__K8S/B_DEPL_SRVC/depl-sba-auth.yaml
# kubectl delete deployments depl-sba-auth
# kubectl delete services srvc-clusterip-sba-auth


#------------------------------------------------------------------------- 
#### (1) API Deployment (Auth) 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: depl-sba-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: srvc-sba-auth
  template:
    metadata:
      labels:
        app: srvc-sba-auth
    spec:
      containers:
        - name: srvc-sba-auth
          image: mansanhhub/srvc-sba-auth
          ports:
            - containerPort: 1102
          env:
            - name: DOTNET_ENVIRONMENT
              value: K8S
            - name: ASPNETCORE_URLS
              value: http://+:1102
            - name: ConnectionStrings__SqlConnection
              value: "Server=srvc-clusterip-mssql-sba-all-dev,1433;Initial Catalog=SBA_Auth;User ID=sa;Password=P@55w0rd!123;TrustServerCertificate=true;"
              # value: "Server=srvc-clusterip-mssql-sba-auth,1433;Initial Catalog=SBA_Auth;User ID=sa;Password=P@55w0rd!123;TrustServerCertificate=true;"

---
#------------------------------------------------------------------------- 
#### (2) API Cluster IP (Auth)
# - We need ClusterIP for Inter Service Communication
# - Production Required
# kubectl port-forward svc/srvc-clusterip-sba-auth 1102:1102
# http://localhost:1102/api/Auth/v1/swagger/index.html
# http://localhost:1102/api/Auth/v1/_projectz-lookup/gets-lookup

apiVersion: v1
kind: Service
metadata:
  name: srvc-clusterip-sba-auth
spec:
  type: ClusterIP
  selector:
    app: srvc-sba-auth
  ports:
  - name: srvc-sba-auth
    protocol: TCP
    port: 1102
    targetPort: 1102
    # nodePort: Not a Valid Option for Cluster IP

---
#-------------------------------------------------------------------------
#### (3) API Node Port (Auth)
# - We need NodePort for External Service Access
# - No Production Required
apiVersion: v1
kind: Service
metadata:
  name: srvc-np-sba-auth
spec:
  type: NodePort
  selector:
    app: srvc-sba-auth
  ports:
    - name: srvc-sba-auth
      protocol: TCP
      port: 1102 # Node Port
      targetPort: 1102 # Pod's App port
      nodePort: 31102 # 30000-32767 (Host Port)

## ROUTES (K8S Node Port)
# - http://localhost:31102/api/Auth/v1/swagger/index.html
# - http://localhost:31102/api/Auth/v1/_projectz-lookupz/gets-lookup