namespace GLOB.Domain.Base;

public class EntityShortProjectz : EntityBase
{
  // Generated by End User (PayStatus-Active, PayStatus-Deactive, Guids, 001-0002-0003)
  // Pregenerated Key Because of Applying Conditions on (Backend / FrontEnd)
  public string KeyId { get; set; } 
  public int? EntityShortParentId { get; set; }
  public virtual EntityShortParentProjectz? EntityShortParentProjectz { get; set; }
}
