namespace GLOB.Domain.Base;

public class EntityShortProjectz : EntityBase
{
  public string KeyId { get; set; } // Generated by End User (PayStatus-Active, PayStatus-Deactive, Guids, 001-0002-0003)
  public int? EntityShortParentId { get; set; }
  public virtual EntityShortParentProjectz? EntityShortParentProjectz { get; set; }
}
