namespace GLOB.Domain.Base;

public class ProjectzLookup : EntityBase
{
  // Generated by End User (PayStatus-Active, PayStatus-Deactive, Guids, 001-0002-0003)
  // Pregenerated Key Because of Applying Conditions on (Backend / FrontEnd)
  public string? Code { get; set; } = null;
  public int? ProjectzLookupBaseId { get; set; }
  public virtual ProjectzLookupBase? ProjectzLookupBase { get; set; }
}

public class ProjectzLookupDtoRead : DtoRead
{
  public int ProjectzLookupBaseId { get; set; }
  public DtoSelect? ProjectzLookupBase { get; set; }
}
public class ProjectzLookupDtoCreate : DtoCreate
{
  public int ProjectzLookupBaseId { get; set; }
}
public class ProjectzLookupDtoSearch : DtoSearch
{
  public string Code { get; set; } 
  public int? ProjectzLookupBaseId { get; set; }
}