namespace GLOB.Domain.Base;

public class ProjectzEntityShort : EntityBase
{
  // Generated by End User (PayStatus-Active, PayStatus-Deactive, Guids, 001-0002-0003)
  // Pregenerated Key Because of Applying Conditions on (Backend / FrontEnd)
  public string KeyId { get; set; } 
  public int? ProjectzEntityShortParentId { get; set; }
  public virtual ProjectzEntityShortParent? ProjectzEntityShortParent { get; set; }
}
