namespace GLOB.Domain.Base;

public class ProjectzEntityLookup : EntityBase
{
  // Generated by End User (PayStatus-Active, PayStatus-Deactive, Guids, 001-0002-0003)
  // Pregenerated Key Because of Applying Conditions on (Backend / FrontEnd)
  public string? Code { get; set; } = null;
  public int? ProjectzEntityLookupBaseId { get; set; }
  public virtual ProjectzEntityLookupBase? ProjectzEntityLookupBase { get; set; }
}

public class ProjectzEntityDtoRead : DtoRead
{
  public int ProjectzEntityLookupBaseId { get; set; }
  public DtoSelect? ProjectzEntityLookupBase { get; set; }
}
public class ProjectzEntityDtoCreate : DtoCreate
{
  public int ProjectzEntityLookupBaseId { get; set; }
}
public class ProjectzEntityDtoSearch : DtoSearch
{
  public string Code { get; set; } 
  public int? ProjectzEntityLookupBaseId { get; set; }
}