using System.ComponentModel.DataAnnotations.Schema;

namespace GLOB.Domain.Base;

public class ProjectzLookupzz : EntityBase
{
  // Generated by End User (PayStatus-Active, PayStatus-Deactive, Guids, 001-0002-0003)
  // Pregenerated Key Because of Applying Conditions on (Backend / FrontEnd)
  public string? Code { get; set; } = null;
  [ForeignKey(nameof(ProjectzLookupzzBase))]
  public int? ProjectzLookupzzBaseId { get; set; }
  [ForeignKey("ProjectzLookupzzBaseId")]
  public virtual ProjectzLookupzzBase? ProjectzLookupzzBase { get; set; }
}

public class ProjectzLookupzzDtoRead : DtoRead
{
  public string? Code { get; set; } = null;
  public int ProjectzLookupzzBaseId { get; set; }
  public DtoSelect? ProjectzLookupzzBase { get; set; }
}
public class ProjectzLookupzzDtoCreate : DtoCreate
{
  public string? Code { get; set; } = null;
  public int ProjectzLookupzzBaseId { get; set; }
}
public class ProjectzLookupzzDtoSearch : DtoSearch
{
  public string? Code { get; set; } 
  public int? ProjectzLookupzzBaseId { get; set; }
}