using System.ComponentModel.DataAnnotations.Schema;

namespace GLOB.Domain.Base;

public class ProjectzLookupz : EntityBase
{
  // Generated by End User (PayStatus-Active, PayStatus-Deactive, Guids, 001-0002-0003)
  // Pregenerated Key Because of Applying Conditions on (Backend / FrontEnd)
  public string? Code { get; set; } = null;
  [ForeignKey(nameof(ProjectzLookupzBase))]
  public int? ProjectzLookupzBaseId { get; set; }
  [ForeignKey("ProjectzLookupzBaseId")]
  public virtual ProjectzLookupzBase? ProjectzLookupzBase { get; set; }
}

public class ProjectzLookupzDtoRead : DtoRead
{
  public string? Code { get; set; } = null;
  public int ProjectzLookupzBaseId { get; set; }
  public DtoSelect? ProjectzLookupzBase { get; set; }
}
public class ProjectzLookupzDtoCreate : DtoCreate
{
  public string? Code { get; set; } = null;
  public int ProjectzLookupzBaseId { get; set; }
}
public class ProjectzLookupzDtoSearch : DtoSearch
{
  public string? Code { get; set; } 
  public int? ProjectzLookupzBaseId { get; set; }
}