# Get Base Image Full .NET SDK
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS base
WORKDIR /app

# Copy csproj and restore dependencies
COPY *.csproj ./
RUN dotnet restore

# Copy everything else and build
COPY . ./
RUN dotnet publish -c Release -o out

# Generate Runtime Image
FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS final
WORKDIR /app
# EXPOSE 5101
COPY --from=base /app/out .

ENV ASPNETCORE_URLS="http://+:5101"
ENV DOTNET_ENVIRONMENT="Docker-501"

ENTRYPOINT ["dotnet", "PlatformService.dll"]


# Better Approach
# # Stage 1: Build
# FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
# WORKDIR /src

# # Copy .csproj and restore dependencies
# COPY *.csproj ./
# RUN dotnet restore

# # Copy all files and build the application
# COPY . ./
# RUN dotnet publish -c Release -o /app/publish

# # Stage 2: Runtime
# FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS runtime
# WORKDIR /app
# EXPOSE 5101

# # Copy the built application from the build stage
# COPY --from=build /app/publish ./

# # Set the entry point
# ENTRYPOINT ["dotnet", "PlatformService.dll"]
