using System.ComponentModel.DataAnnotations.Schema;
using GLOB.Domain.Base;

namespace GLOB.Hierarchy.Global;

public class GlobalLookupzz : EntityBase
{
  // Generated by End User (PayStatus-Active, PayStatus-Deactive, Guids, 001-0002-0003)
  // Pregenerated Key Because of Applying Conditions on (Backend / FrontEnd)
  public string? Code { get; set; } = null;
  [ForeignKey(nameof(GlobalLookupzzBase))]
  public int? GlobalLookupzzBaseId { get; set; }
  [ForeignKey("GlobalLookupzzBaseId")]
  public virtual GlobalLookupzzBase? GlobalLookupzzBase { get; set; }
}

public class GlobalLookupzzDtoRead : DtoRead
{
  public string? Code { get; set; } = null;
  public int GlobalLookupzzBaseId { get; set; }
  public DtoSelect? GlobalLookupzzBase { get; set; }
}
public class GlobalLookupzzDtoCreate : DtoCreate
{
  public string? Code { get; set; } = null;
  public int GlobalLookupzzBaseId { get; set; }
}
public class GlobalLookupzzDtoSearch : DtoSearch
{
  public string? Code { get; set; } 
  public int? GlobalLookupzzBaseId { get; set; }
}