using System.ComponentModel.DataAnnotations.Schema;
using GLOB.Domain.Base;

namespace GLOB.Hierarchy.Global;

public class GlobalLookupz : EntityBase
{
  // Generated by End User (PayStatus-Active, PayStatus-Deactive, Guids, 001-0002-0003)
  // Pregenerated Key Because of Applying Conditions on (Backend / FrontEnd)
  public string? Code { get; set; } = null;
  [ForeignKey(nameof(GlobalLookupzBase))]
  public int? GlobalLookupzBaseId { get; set; }
  [ForeignKey("GlobalLookupzBaseId")]
  public virtual GlobalLookupzBase? GlobalLookupzBase { get; set; }
}

public class GlobalLookupzDtoRead : DtoRead
{
  public string? Code { get; set; } = null;
  public int GlobalLookupzBaseId { get; set; }
  public DtoSelect? GlobalLookupzBase { get; set; }
}
public class GlobalLookupzDtoCreate : DtoCreate
{
  public string? Code { get; set; } = null;
  public int GlobalLookupzBaseId { get; set; }
}
public class GlobalLookupzDtoSearch : DtoSearch
{
  public string? Code { get; set; } 
  public int? GlobalLookupzBaseId { get; set; }
}