################~~~~ SBA Auth ~~~~~##################
# - Deployment
# - ClusterIP
# - Node Port

## BASH BUILD Dockerfile
## -t tagname, -f file/reference, ./buildContext  
# docker build -t mansanhhub/srvc-sba-auth -f Projects/SBA.Auth/Dockerfile .
# docker push mansanhhub/srvc-sba-auth
# docker pull mansanhhub/srvc-sba-auth

#------------------------------------------------------------------------- 
## BASH RUN Deployment srvc-sba-auth
# kubectl apply -f ./__/K8S/B_DEPL_SRVC/depl-sba-auth.yaml
# kubectl get pods
# kubectl get deployments
# kubectl logs -l app=srvc-sba-auth --all-containers=true --tail=-1
# kubectl rollout restart deployments depl-sba-auth

## BASH DELETE (Deployments & Service)8
# kubectl delete -f ./__/K8S/B_DEPL_SRVC/depl-sba-auth.yaml
# kubectl delete deployments depl-sba-auth
# kubectl delete services srvc-cip-sba-auth
#------------------------------------------------------------------------- 
#### (1) API Deployment (Auth) 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: depl-sba-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: srvc-sba-auth
  template:
    metadata:
      labels:
        app: srvc-sba-auth
    spec:
      enableServiceLinks: false   # ✅ disables auto-injected env vars
      containers:
        - name: srvc-sba-auth
          image: mansanhhub/srvc-sba-auth
          imagePullPolicy: Always
          ports:
            - containerPort: 1104
          env:
            - name: DOTNET_ENVIRONMENT
              value: K8S
            - name: ASPNETCORE_URLS
              value: http://+:1104
              
            - name: ConnectionStrings__Redis
              value: "srvc-cip-redis-sba-dev:6379,password=P@55w0rd!123"
            - name: ConnectionStrings__SqlConnection
              value: "Server=srvc-cip-mssql-sba-dev.default.svc.cluster.local,1433;Initial Catalog=SBA_Auth;User ID=sa;Password=P@55w0rd!123;TrustServerCertificate=true;"
            
            - name: Clients__Http_Host__Gateway
              value: http://srvc-cip-sba-gateway:1100
            - name: Clients__Http_Host__Auth
              value: http://srvc-cip-sba-auth:1104


            - name: Clients__RabbitMQz__HostName
              value: srvc-cip-rbmq-sba.default.svc.cluster.local
            - name: Clients__RabbitMQz__Port
              value: "5672"
            - name: Clients__RabbitMQz__VirtualHost
              value: /
            - name: Clients__RabbitMQz__Username
              value: guest
            - name: Clients__RabbitMQz__Password
              value: guest
            # - name: Clients__RabbitMQz__Uri
            #   value: amqp://guest:guest@srvc-cip-rbmq-sba.default.svc.cluster.local/
---
#------------------------------------------------------------------------- 
#### (2) API Cluster IP (Auth)
# - We need ClusterIP for Inter Service Communication
# - Production Required
# kubectl port-forward svc/srvc-cip-sba-auth 1104:1104
# http://srvc-cip-sba-auth:1104/api/Auth/v1/swagger/index.html
# http://srvc-cip-sba-auth:1104/api/Auth/v1/_projectz-lookup/gets-lookup
---
apiVersion: v1
kind: Service
metadata:
  name: srvc-cip-sba-auth
spec:
  type: ClusterIP
  selector:
    app: srvc-sba-auth
  ports:
  - name: srvc-sba-auth
    protocol: TCP
    port: 1104
    targetPort: 1104
    # nodePort: Not a Valid Option for Cluster IP

---
#-------------------------------------------------------------------------
#### (3) API Node Port (Auth)
# - We need NodePort for External Service Access
# - No Production Required
apiVersion: v1
kind: Service
metadata:
  name: srvc-np-sba-auth
spec:
  type: NodePort
  selector:
    app: srvc-sba-auth
  ports:
    - name: srvc-sba-auth
      protocol: TCP
      port: 1104 # Node Port
      targetPort: 1104 # Pod's App port
      nodePort: 31104 # 30000-32767 (Host Port)

## ROUTES (K8S Node Port)
# - http://localhost:31104/api/Auth/v1/swagger/index.html
# - http://localhost:31104/api/Auth/v1/_projectz-lookup/gets-lookup