################~~~~ SBA APIGateway ~~~~~##################
# - Deployment
# - ClusterIP
# - Node Port

## BASH BUILD Dockerfile
## -t tagname, -f file/reference, ./buildContext  
# docker build -t mansanhhub/srvc-sba-gateway -f Projects/SBA.APIGateway/Dockerfile .
# docker push mansanhhub/srvc-sba-gateway
# docker pull mansanhhub/srvc-sba-gateway

#------------------------------------------------------------------------- 
## BASH RUN Deployment srvc-sba-gateway
# kubectl apply -f ./__/K8S/B_DEPL_SRVC/depl-sba-gateway.yaml
# kubectl get pods
# kubectl get deployments
# kubectl logs -l app=srvc-sba-gateway --all-containers=true --tail=-1
# kubectl rollout restart deployments depl-sba-gateway

## BASH DELETE (Deployments & Service)8
# kubectl delete -f ./__/K8S/B_DEPL_SRVC/depl-sba-gateway.yaml
# kubectl delete deployments depl-sba-gateway
# kubectl delete services srvc-cip-sba-gateway
#------------------------------------------------------------------------- 
#### (1) API Deployment (APIGateway)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: depl-sba-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: srvc-sba-gateway
  template:
    metadata:
      labels:
        app: srvc-sba-gateway
    spec:
      enableServiceLinks: false   # ✅ disables auto-injected env vars
      containers:
        - name: srvc-sba-gateway
          image: mansanhhub/srvc-sba-gateway
          imagePullPolicy: Always
          ports:
            - containerPort: 1100
          env:
            - name: DOTNET_ENVIRONMENT
              value: K8S
            - name: ASPNETCORE_URLS
              value: http://+:1100
            - name: OcelotFileName
              value: ocelot.K8S.json

---
#------------------------------------------------------------------------- 
#### (2) API Cluster IP (APIGateway)
# - We need ClusterIP for Inter Service Communication
# - Production Required
# kubectl port-forward svc/srvc-cip-sba-gateway 1100:1100
# http://localhost:1100/api/Gateway/v1/swagger/index.html
# http://localhost:1100/api/Hierarchy/v1/_projectz-lookup/gets-lookup

apiVersion: v1
kind: Service
metadata:
  name: srvc-cip-sba-gateway
spec:
  type: ClusterIP
  selector:
    app: srvc-sba-gateway
  ports:
  - name: srvc-sba-gateway
    protocol: TCP
    port: 1100
    targetPort: 1100
    # nodePort: Not a Valid Option for Cluster IP

---
#-------------------------------------------------------------------------
#### (3) API Node Port (APIGateway)
# - We need NodePort for External Service Access
# - No Production Required
apiVersion: v1
kind: Service
metadata:
  name: srvc-np-sba-gateway
spec:
  type: NodePort
  selector:
    app: srvc-sba-gateway
  ports:
    - name: srvc-sba-gateway
      protocol: TCP
      port: 1100 # Node Port
      targetPort: 1100 # Pod's App port
      nodePort: 31100 # 30000-32767 (Host Port)

## ROUTES (K8S Node Port)
# - http://localhost:1100/api/Gateway/v1/swagger/index.html
# - http://localhost:31100/api/Gateway/v1/swagger/index.html