// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlatformService.Data;

#nullable disable

namespace PlatformService.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PlatformService.Models.Employee", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Gender = "Male",
                            Name = "Ahsan"
                        },
                        new
                        {
                            ID = 2,
                            Gender = "Male",
                            Name = "Asim"
                        },
                        new
                        {
                            ID = 3,
                            Gender = "Female",
                            Name = "Sumaya"
                        });
                });

            modelBuilder.Entity("PlatformService.Models.Platform", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Cost")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Platforms");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Cost = "Free",
                            Name = "Dot Net",
                            Publisher = "Microsoft"
                        },
                        new
                        {
                            ID = 2,
                            Cost = "Free",
                            Name = "SQL Server Express",
                            Publisher = "Microsoft"
                        },
                        new
                        {
                            ID = 3,
                            Cost = "Free",
                            Name = "Kubernetes",
                            Publisher = "Cloud Native Computing Foundation"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
